#
# A GitHub workflow to run NPM based builds and tests for every push
#
# help:
# - original gist: https://gist.github.com/robb-j/049217ca8cecf4e214b8b82123f7371b
# - https://docs.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
#

name: Node.js automated tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm ci

      - name: run the build
        run: npm run build --if-present

      - name: run tests
        run: npm test
        env:
          CI: true
